config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  devise_for :users
  resources :students
  resources :student_companies
  resources :cash_management_tables
  resources :companies
  resources :cash_in_histories
  resources :cash_out_histories
  get 'home', to: 'home#index'
  get '/get_company_details' => 'student_companies#get_company_details'
  get '/fetch_current_user_companies' => 'student_companies#fetch_current_user_companies'
  namespace :api do
    namespace :v1 do
      resources :students
      resources :student_companies
      resources :cash_management_tables
      resources :companies
      resources :cash_in_histories
      resources :cash_out_histories
      get 'home', to: 'home#index'
      post 'auth_user', to: 'authentication#authenticate_user'

      devise_for :users, controllers: { registrations: 'registrations' , sessions: 'sessions'}

      post '/sign_in' , to:'users#login'
      get '/auto_login' => 'users#auto_login'
      get '/get_company_details' => 'student_companies#get_company_details'


    end
    namespace :v2 do
      # Things yet to come
    end
  end  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/student_company.rb
class StudentCompany < ApplicationRecord
  belongs_to :student
  belongs_to :company
  has_one :cash_management_table

end

app/controllers/api/v1/student_companies_controller.rb
class Api::V1::StudentCompaniesController < ApiController
  before_action :authenticate_request!

  # skip_before_action :authenticate_user!, only: [:action_to_skip_here]

  before_action :set_student_company, only: [:show, :update, :destroy]

  def index
    @student_companies = StudentCompany.all
    render json: @student_companies
  end

  def show
    render json: @student_company
  end

  def create
    @student_company = StudentCompany.new(student_company_params)
    if @student_company.save
      render json: @student_company, status: :created
    else
      render json: @student_company.errors, status: 400
    end
  end

  def update
    if @student_company.update(student_params)
      render json: {message: "Student Company Updated Successfully"}, status: 200
    else
      render json: @student_company.errors, status: 400
    end
  end

  def destroy
    if @student_company
      @student_company.destroy
      render json: {message: "Student Company Deleted Successfully"}, status: 200
    else
      render json: {error: "Unable  to Delete"}, status: 400
    end

  end

  def get_company_details
    student_companies = StudentCompany.where(student_id: @current_user.id)
    student_cash_management_tables = CashManagementTable.find_by(student_company_id: student_companies.pluck(:id))
    student_cash_in_histories = CashInHistory.where(cash_management_table_id: student_cash_management_tables.id)
    student_cash_out_histories = CashOutHistory.where(cash_management_table_id: student_cash_management_tables.id)
    render json: {user:@current_user, student_companies: student_companies,
                  student_cash_management_tables: student_cash_management_tables,
                  student_cash_in_histories: student_cash_in_histories,
                  student_cash_out_histories: student_cash_out_histories,

    }
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_student_company
    @student_company = StudentCompany.find(params[:id])
  end

  # Only allow a trusted parameter “white list” through.
  def student_company_params
    params.require(:student_company).permit(:company_id, :student_id)
  end
end

app/controllers/student_companies_controller.rb
class StudentCompaniesController < ApplicationController
  before_action :authenticate_user!

  # skip_before_action :authenticate_user!, only: [:action_to_skip_here]

  before_action :set_student_company, only: [:show, :update, :destroy, :edit]

  def index
    @student_companies = StudentCompany.all
  end

  def fetch_current_user_companies
    @student_companies = StudentCompany.where(student_id: current_user.id)
  end

  def show
    @student_company
    @cash_management_table = CashManagementTable.find_by(student_company_id: @student_company.id)
    unless @cash_management_table.nil?
    @cash_in_histories = CashInHistory.where(cash_management_table_id: @cash_management_table.id)
    @cash_out_histories = CashOutHistory.where(cash_management_table_id: @cash_management_table.id)
    end
  end

  def new
    @student_company = StudentCompany.new

  end


  def edit
    @student_company
  end


  def create
    @student_company = StudentCompany.create(student_id: current_user.id, company_id: params['student_company']['company_id'])
    if @student_company.save
      flash[:notice] = "Student Company was successfully created"
      redirect_to @student_company
    else
      render 'new'
    end
  end

  def update
    if @student_company.update(student_params)
      redirect_to cash_management_table_path
    else
      render 'edit'
    end
  end

  def destroy
    if @student_company
      @student_company.destroy
      redirect_to fetch_current_user_companies_path
    end


  end

  def get_company_details
    student_companies = StudentCompany.where(student_id: params[:student_id], company_id: params[:company_id])
    student_cash_management_tables = CashManagementTable.find_by(student_company_id: student_companies.pluck(:id))
    student_cash_in_histories = CashInHistory.where(cash_management_table_id: student_cash_management_tables.id)
    student_cash_out_histories = CashOutHistory.where(cash_management_table_id: student_cash_management_tables.id)
    render json: {user:@current_user, student_companies: student_companies,
                  student_cash_management_tables: student_cash_management_tables,
                  student_cash_in_histories: student_cash_in_histories,
                  student_cash_out_histories: student_cash_out_histories,

    }
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_student_company
    @student_company = StudentCompany.find(params[:id])
  end

  # Only allow a trusted parameter “white list” through.
  # def student_company_params
  #   params.require(:student_company).permit(:company_id, :student_id)
  # end
end

app/views/student_companies/_form.html.erb
<div style="text-align: center">

  <%= form_with model: @student_company, local: true do |form| %>

  <% if @student_company.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@student_company.errors.count, "error") %> prohibited
        this student company from being saved:
      </h2>
      <ul>
        <% @student_company.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= form.label :company_name %><br />
    <%= form.select :company_id, options_for_select(Company.where.not(id: StudentCompany.where(student_id: current_user.id).pluck(:company_id)).map{|s|[s.name, s.id]}) %>
  </div>


  <p>
    <%= form.submit %>
  </p>

<% end %>
</div>

app/views/student_companies/edit.html.erb
<h1 style="text-align: center">Edit Student Company</h1>

<%= render 'form' %>


<%= link_to 'Back', fetch_current_user_companies_path, class: "btn btn-xs btn-danger" %>

app/views/student_companies/fetch_current_user_companies.html.erb
<h1 style="text-align: center">Listing My Companies</h1>

<p style="text-align: center"><%= link_to 'New Student Company', new_student_company_path, class: "btn btn-xs btn-success" %></p>

<table class="table table-bordered" style="width: 300px; margin: auto">
  <tr>
    <th>ID</th>
    <th>Company ID</th>
    <th>Actions</th>
  </tr>

  <% @student_companies.each do |company| %>
    <tr>
      <td><%= company.id %></td>
      <td><%= company.company.name %></td>
      <td><%= link_to 'Show', student_company_path(company),  class: "btn btn-xs btn-success" %>
            <%#= link_to 'Edit', edit_student_company_path(company),  class: "btn btn-xs btn-primary" %>
            <%= link_to 'Delete', student_company_path(company), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-xs btn-danger" %></td>


    </tr>
  <% end %>
</table>

app/views/student_companies/index.html.erb
<h1 style="text-align: center">Listing Student Companies</h1>


<table class="table table-bordered" style="width: 300px; margin: auto">
  <tr>
    <th>ID</th>
    <th>Student Name</th>
    <th>Company Name</th>
  </tr>

  <% @student_companies.each do |company| %>
    <tr>
      <td><%= company.id %></td>
      <td><%= company.student.first_name %></td>
        <% unless company.company.nil? %>
      <td><%= company.company.name %></td>
      <% end %>
<!--      <td><%#= link_to 'Edit', edit_student_company_path(company),  class: "btn btn-xs btn-primary" %></td>-->
<!--      <td><%#= link_to 'Delete', student_company_path(company), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-xs btn-danger" %></td>-->

    </tr>
  <% end %>
</table>

app/views/student_companies/new.html.erb
<h1 style="text-align: center">New Student Company</h1>


<%= render 'form' %>


<%= link_to 'Back', fetch_current_user_companies_path, class: "btn btn-xs btn-danger" %>

app/views/student_companies/show.html.erb
<p style="text-align: center">
  <strong>Comapany Name:</strong>
  <%= @student_company.company.name %>
</p>

<p style="text-align: center">
  <strong> Currency:</strong>
  <%= @student_company.company.currency %>
</p>

<p style="text-align: center">
  <strong>Country:</strong>
  <%= @student_company.company.country %>
</p>



<% if @cash_management_table.nil? %>

  <%= link_to 'Create Cash Management', new_cash_management_table_path(:student_company_id => @student_company.id), class: "btn btn-xs btn-success" %>

<%  else  %>

<!--<table>-->
<!--  <tr>-->
<!--    <th>ID</th>-->
<!--    <th></th>-->
<!--  </tr>-->

<!--  <tr>-->
<!--    <td><%#=  @cash_management_table.id  %></td>-->
<!--    <td><%#= link_to 'Show', cash_management_table_path(@cash_management_table.id),  class: "btn btn-xs btn-success" %></td>-->

<!--  </tr>-->
<!--</table>-->


  <br>


  <p style="text-align: center">
    <strong>Initial Cash:</strong>
    <%= @cash_management_table.initial_cash %>
  </p>

  <p style="text-align: center"><%= link_to 'Create Cash In History of this day', new_cash_in_history_path(:cash_management_table_id => @cash_management_table.id), class: "btn btn-xs btn-success" %></p>

  <br>

  <% if @cash_in_histories.empty? %>

    <table class="table table-bordered">
      <tr>
        <th>ID</th>
        <th>Revenues Amount</th>
        <th>Equity Amount</th>
        <th>Convertible Note Amount</th>
        <th>Bank Debt Amount</th>
        <th>Other Amount</th>
        <th>Status</th>
      </tr>

      <tr>
        <td>No Data</td>
        <td>No Data</td>
        <td>No Data</td>
        <td>No Data</td>
        <td>No Data</td>
        <td>No Data</td>
        <td>No Data</td>
      </tr>
    </table>
  <%  else  %>


    <table class="table table-bordered">
      <tr>
        <th>ID</th>
        <th>Revenues Amount</th>
        <th>Equity Amount</th>
        <th>Convertible Note Amount</th>
        <th>Bank Debt Amount</th>
        <th>Other Amount</th>
        <th>Status</th>
        <th>Actions</th>
      </tr>

      <% @cash_in_histories.each do |history| %>
        <tr>
          <td><%= history.id %></td>
          <td><%= history.revenues_amount %></td>
          <td><%= history.equity_amount %></td>
          <td><%= history.convertible_note_amount %></td>
          <td><%= history.bank_debt_amount %></td>
          <td><%= history.other_amount %></td>
          <td><%= history.status %></td>

          <td><%= link_to 'Edit', edit_cash_in_history_path(history.id, :cash_management_table_id => @cash_management_table.id),  class: "btn btn-xs btn-primary" %>
          <%= link_to 'Delete', cash_in_history_path(history.id, :cash_management_table_id => @cash_management_table.id),
                          method: :delete,
                          data: { confirm: 'Are you sure?' }, class: "btn btn-xs btn-danger" %></td>



        </tr>
      <% end %>
    </table>
  <% end %>

  <p style="text-align: center"><%= link_to 'Create Cash OUT History of this day', new_cash_out_history_path(:cash_management_table_id => @cash_management_table.id), class: "btn btn-xs btn-success" %></p>

  <br>

  <% if @cash_out_histories.empty? %>

    <table class="table table-bordered">
      <tr>
        <th>ID</th>
        <th>Cogs Amount</th>
        <th>Employees Amount</th>
        <th>Services Amount</th>
        <th>Operating Expenses Amount</th>
        <th>Investment Amount</th>
        <th>Status</th>
      </tr>

      <tr>
        <td>No Data</td>
        <td>No Data</td>
        <td>No Data</td>
        <td>No Data</td>
        <td>No Data</td>
        <td>No Data</td>
        <td>No Data</td>
      </tr>
    </table>

  <%  else  %>



    <table class="table table-bordered">
      <tr>
        <th>ID</th>
        <th>Cogs Amount</th>
        <th>Employees Amount</th>
        <th>Services Amount</th>
        <th>Operating Expenses Amount</th>
        <th>Investment Amount</th>
        <th>Status</th>
        <th>Actions</th>
      </tr>

      <% @cash_out_histories.each do |history| %>
        <tr>
          <td><%= history.id %></td>
          <td><%= history.cogs_amount %></td>
          <td><%= history.employees_amount %></td>
          <td><%= history.services_amount %></td>
          <td><%= history.operating_expenses_amount %></td>
          <td><%= history.investments_amount %></td>
          <td><%= history.status %></td>

          <td><%= link_to 'Edit', edit_cash_out_history_path(history.id,  :cash_management_table_id => @cash_management_table.id),  class: "btn btn-xs btn-primary" %>
<%= link_to 'Delete', cash_out_history_path(history.id,  :cash_management_table_id => @cash_management_table.id),
                          method: :delete,
                          data: { confirm: 'Are you sure?' }, class: "btn btn-xs btn-danger" %></td>



        </tr>
      <% end %>
    </table>
  <% end %>

  

<% end %>




<%= link_to 'Back', fetch_current_user_companies_path,  class: "btn btn-xs btn-danger" %>