config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  devise_for :users
  resources :students
  resources :student_companies
  resources :cash_management_tables
  resources :companies
  resources :cash_in_histories
  resources :cash_out_histories
  get 'home', to: 'home#index'
  get '/get_company_details' => 'student_companies#get_company_details'
  get '/fetch_current_user_companies' => 'student_companies#fetch_current_user_companies'
  namespace :api do
    namespace :v1 do
      resources :students
      resources :student_companies
      resources :cash_management_tables
      resources :companies
      resources :cash_in_histories
      resources :cash_out_histories
      get 'home', to: 'home#index'
      post 'auth_user', to: 'authentication#authenticate_user'

      devise_for :users, controllers: { registrations: 'registrations' , sessions: 'sessions'}

      post '/sign_in' , to:'users#login'
      get '/auto_login' => 'users#auto_login'
      get '/get_company_details' => 'student_companies#get_company_details'


    end
    namespace :v2 do
      # Things yet to come
    end
  end  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/api/v1/cash_management_tables_controller.rb
class Api::V1::CashManagementTablesController < ApiController
  before_action :authenticate_request!

  # skip_before_action :authenticate_user!, only: [:action_to_skip_here]

  before_action :set_cash_management_table, only: [:show, :update, :destroy]

  def index
    @cash_management_tables = CashManagementTable.all
    render json: @cash_management_tables
  end

  def show
    render json: @cash_management_table
  end

  def create
    @cash_management_table = CashManagementTable.new(cash_management_table_params)
    if @cash_management_table.save
      render json: @cash_management_table, status: :created
    else
      render json: @cash_management_table.errors, status: 400
    end
  end

  def update
    if @cash_management_table.update(cash_management_table_params)
      render json: {message: "Cash Management Table Updated Successfully"}, status: 200
    else
      render json: @cash_management_table.errors, status: 400
    end
  end

  def destroy
    if @cash_management_table
      @cash_management_table.destroy
      render json: {message: "Cash Management Table Deleted Successfully"}, status: 200
    else
      render json: {error: "Unable  to Delete"}, status: 400
    end

  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_cash_management_table
    @cash_management_table = CashManagementTable.find(params[:id])
  end

  # Only allow a trusted parameter “white list” through.
  def cash_management_table_params
    params.require(:cash_management_table).permit(:cash_in, :cash_out, :initial_cash, :student_company_id)
  end
end

app/controllers/cash_management_tables_controller.rb
class CashManagementTablesController < ApplicationController
  before_action :authenticate_user!

  # skip_before_action :authenticate_user!, only: [:action_to_skip_here]

  before_action :set_cash_management_table, only: [:show, :update, :destroy]

  def index
    student_companies = StudentCompany.where(student_id: current_user.id)
    @cash_management_tables = CashManagementTable.where(student_company_id: student_companies.pluck(:id))
    render json: @cash_management_tables

  end

  def show
    @cash_management_table
    @cash_in_histories = CashInHistory.where(cash_management_table_id: @cash_management_table.id)
    @cash_out_histories = CashOutHistory.where(cash_management_table_id: @cash_management_table.id)
  end

  def new
    @student_company_id = params[:student_company_id]
    @cash_management_table = CashManagementTable.new

  end

  def create
    @cash_management_table = CashManagementTable.new(cash_management_table_params)
    if @cash_management_table.save
      flash[:notice] = "CashManagement Table was successfully created"
      redirect_to @cash_management_table
    else
      render 'new'
    end
  end



  def update
    if @cash_management_table.update(cash_management_table_params)
      redirect_to @cash_management_table
    else
      render 'edit'
  end
  end

  def destroy
    if @cash_management_table
      @cash_management_table.destroy
      redirect_to fetch_current_user_companies_path
  end

  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_cash_management_table
    @cash_management_table = CashManagementTable.find(params[:id])
  end

  # Only allow a trusted parameter “white list” through.
  def cash_management_table_params
    params.require(:cash_management_table).permit(:cash_in, :cash_out, :initial_cash, :student_company_id)
  end
end

app/views/cash_management_tables/_form.html.erb
<div style="text-align: center">
<%= form_with model: @cash_management_table, local: true do |form| %>

  <% if @cash_management_table.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@cash_management_table.errors.count, "error") %> prohibited
        this table from being saved:
      </h2>
      <ul>
        <% @cash_management_table.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :initial_cash %><br>
    <%= form.text_field :initial_cash %>
    <%= form.hidden_field :student_company_id, value: @student_company_id %>

  </p>



  <p>
    <%= form.submit %>
  </p>

<% end %>
</div>

app/views/cash_management_tables/edit.html.erb
<h1 style="text-align: center">Edit Company</h1>

<%= render 'form' %>


<%= link_to 'Back', companies_path,  class: "btn btn-xs btn-danger" %>

app/views/cash_management_tables/index.html.erb
<h1>Listing Comapnies</h1>

<%= link_to 'New Company', new_company_path, class: "btn btn-xs btn-success" %>

<table>
  <tr>
    <th>Name</th>
    <th></th>
  </tr>

  <% @companies.each do |company| %>
    <tr>
      <td><%= company.name %></td>
      <td><%= link_to 'Show', company_path(company),  class: "btn btn-xs btn-success" %></td>
      <td><%= link_to 'Edit', edit_company_path(company),  class: "btn btn-xs btn-primary" %></td>
      <td><%= link_to 'Delete', company_path(company),
                      method: :delete,
                      data: { confirm: 'Are you sure?' }, class: "btn btn-xs btn-danger" %></td>

    </tr>
  <% end %>
</table>

app/views/cash_management_tables/new.html.erb
<h1 style="text-align: center">New Cash In History</h1>


<%= render 'form' %>


<%= link_to 'Back', student_companies_path,  class: "btn btn-xs btn-danger" %>

app/views/cash_management_tables/show.html.erb
<p>
  <strong>Initial Cash:</strong>
  <%= @cash_management_table.initial_cash %>
</p>

<%= link_to 'Create Cash In History of this day', new_cash_in_history_path(:cash_management_table_id => @cash_management_table.id), class: "btn btn-xs btn-success" %>
<%= link_to 'Create Cash OUT History of this day', new_cash_out_history_path(:cash_management_table_id => @cash_management_table.id), class: "btn btn-xs btn-success" %>


<% if @cash_in_histories.empty? %>

  <table>
    <tr>
      <th>ID</th>
      <th></th>
    </tr>

    <tr>
      <td>No Data</td>
    </tr>
  </table>
<%  else  %>


  <table class="table table-bordered">
    <tr>
      <th>ID</th>
      <th>Revenues Amount</th>
      <th>Equity Amount</th>
      <th>Convertible Note Amount</th>
      <th>Bank Debt Amount</th>
      <th>Other Amount</th>
      <th>Status</th>
      <th>Actions</th>
    </tr>

    <% @cash_in_histories.each do |history| %>
      <tr>
        <td><%= history.id %></td>
        <td><%= history.revenues_amount %></td>
        <td><%= history.equity_amount %></td>
        <td><%= history.convertible_note_amount %></td>
        <td><%= history.bank_debt_amount %></td>
        <td><%= history.other_amount %></td>
        <td><%= history.status %></td>

        <td><%= link_to 'Edit', edit_cash_in_history_path(history.id, :cash_management_table_id => @cash_management_table.id),  class: "btn btn-xs btn-primary" %>
        <%= link_to 'Delete', cash_in_history_path(history.id, :cash_management_table_id => @cash_management_table.id),
                        method: :delete,
                        data: { confirm: 'Are you sure?' }, class: "btn btn-xs btn-danger" %></td>



      </tr>
    <% end %>
  </table>
<% end %>


<% if @cash_out_histories.empty? %>

  <table>
    <tr>
      <th>ID</th>
      <th></th>
    </tr>

    <tr>
      <td>No Data</td>
    </tr>
  </table>

<%  else  %>



  <table class="table table-bordered">
    <tr>
      <th>ID</th>
      <th>Cogs Amount</th>
      <th>Employees Amount</th>
      <th>Services Amount</th>
      <th>Operating Expenses Amount</th>
      <th>Investment Amount</th>
      <th>Status</th>
      <th>Actions</th>
    </tr>

    <% @cash_out_histories.each do |history| %>
      <tr>
        <td><%= history.id %></td>
        <td><%= history.cogs_amount %></td>
        <td><%= history.employees_amount %></td>
        <td><%= history.services_amount %></td>
        <td><%= history.operating_expenses_amount %></td>
        <td><%= history.investments_amount %></td>
        <td><%= history.status %></td>

        <td><%= link_to 'Edit', edit_cash_out_history_path(history.id,  :cash_management_table_id => @cash_management_table.id),  class: "btn btn-xs btn-primary" %>
<%= link_to 'Delete', cash_out_history_path(history.id,  :cash_management_table_id => @cash_management_table.id),
                        method: :delete,
                        data: { confirm: 'Are you sure?' }, class: "btn btn-xs btn-danger" %></td>



      </tr>
    <% end %>
  </table>
<% end %>



<%= link_to 'Back', fetch_current_user_companies_path %>