config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  devise_for :users
  resources :students
  resources :student_companies
  resources :cash_management_tables
  resources :companies
  resources :cash_in_histories
  resources :cash_out_histories
  get 'home', to: 'home#index'
  get '/get_company_details' => 'student_companies#get_company_details'
  get '/fetch_current_user_companies' => 'student_companies#fetch_current_user_companies'
  namespace :api do
    namespace :v1 do
      resources :students
      resources :student_companies
      resources :cash_management_tables
      resources :companies
      resources :cash_in_histories
      resources :cash_out_histories
      get 'home', to: 'home#index'
      post 'auth_user', to: 'authentication#authenticate_user'

      devise_for :users, controllers: { registrations: 'registrations' , sessions: 'sessions'}

      post '/sign_in' , to:'users#login'
      get '/auto_login' => 'users#auto_login'
      get '/get_company_details' => 'student_companies#get_company_details'


    end
    namespace :v2 do
      # Things yet to come
    end
  end  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <%= link_to "Home", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <% if current_user.role == 'teacher' %>

            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Main
                Items <span class="caret"></span></a>


              <ul class="dropdown-menu">
                <li><%= link_to "Companies", companies_path, class: "navbar-link" %></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to "Students", students_path, class: "navbar-link" %></li>
                <li role="separator" class="divider"></li>
                <li><%= link_to "Student Companies", student_companies_path, class: "navbar-link" %></li>
                <li role="separator" class="divider"></li>

              </ul>
            </li>

          <% else %>
            <li><%= link_to "Student Companies", fetch_current_user_companies_path, class: "navbar-link" %></li>
            <li><%= link_to "All Companies", companies_path, class: "navbar-link" %></li>
          <% end %>
        <% end %>


      </ul>


      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <% if current_user.role == 'teacher' %>
            <p>Logged IN As Teacher</p>
          <% else %>
            <p>Logged IN As Student</p>

          <% end %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email %>
              <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Edit Profile", edit_user_registration_path, :class => 'navbar-link' %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link' %></li>

            </ul>
          </li>
        <% else %>
          <li><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link' %> </li>
          <li><%= link_to "Login", new_user_session_path, :class => 'navbar-link' %></li>
        <% end %>


      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StudentCompanies</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
  <%= render 'layouts/navigation' %>

<!--  <p class="navbar-text float-right">-->
    <%# if user_signed_in? %>
<!--      Logged in as <strong><%#= current_user.email %></strong>.-->
<!--      <%#= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |-->
      <%#= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
    <%# else %>
<!--      <%#= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |-->
      <%#= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
    <%# end %>
<!--  </p>-->

  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>
    <%= yield %>
  </body>
</html>